### ISSUE TITLE
Support multiple poetry scripts

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/poetry-run#10]
Currently we support `pyproject.toml` files containing exactly one script. We can't support more than one script because the buildpack doesn't know which script should be run.

There are a couple of different ways to support multiple scripts:

1. Allow the user to provide a script via an environment variable (e.g. `BP_POETRY_RUN_SCRIPT_NAME` or similar).
2. Run all the scripts in a sequence. This might require some knowledge of how multiple scripts are run (e.g. what shell is executing the scripts). It would also require investigating whether the order of the scripts in `pyproject.toml` is preserved after parsing (i.e. is it a list or a map).
3. Some combination of the above - allowing the user to run multiple scripts in sequence by passing their names in via an environment variable.

**Comment by joshuatcasey** [comment]
@thitch97 can I look into this?

**Comment by joshuatcasey** [comment]
I took a look at how `poetry run` reacts to having multiple scripts.

1. `poetry run` only runs a single script, usually specified by `poetry run <script>`
2. If `poetry run` has no further args, it will attempt to run the script called `run`, as though you had run `poetry run run`.
3. If `poetry run <invalid-script>`, exits with code 1
4. If `poetry run <valid-script>`, will run that script no matter how many scripts are listed.

## Recommendation:
- If `BP_POETRY_RUN_SCRIPT` is specified, the start command should be `poetry run <BP_POETRY_RUN_SCRIPT>`
- If `BP_POETRY_RUN_SCRIPT` is not specified and there is exactly one script, the start command should be `poetry run script-name`
- If `BP_POETRY_RUN_SCRIPT` is not specified and there are zero scripts, detection should fail
- If `BP_POETRY_RUN_SCRIPT` is not specified and there are 2+ scripts, detection should fail

**Comment by joshuatcasey** [comment]
Nice find about running a target from the path. The name change (`_TARGET` instead of `_SCRIPT`) makes sense in that regard. 

We could also use `_COMMAND`, since thaft's actually clearly listed in the docs I just wasn't keyed into what that meant:

https://python-poetry.org/docs/cli/#run

> The run command executes the given command inside the project’s virtualenv.

All that being said, it's not super clear to me when someone would choose to bake this into an image. Since `procfile` also exists in the same order group as `poetry-run` (https://github.com/paketo-buildpacks/python/blob/f0d85fcf91ab15cf7a643ef1258dd84ed1d46696/buildpack.toml#L166-L173) couldn't consumers use that for generic process specifications? It feels like we'd be asking the `poetry-run` buildpack to run some thing other than the application code, although that of course would only happen when the buildpack user explicitly asked for it.

**Comment by robdimsdale** [comment]
Yes, though the poetry documentation you linked to implicitly decouples commands from scripts, so I suggested `_TARGET` because it encompasses both options.

I agree that a user could use a procfile, but then they'd have to create the `Procfile`, and know the syntax. Adding a procfile would also require re-building the app. The use-case I have in mind is running a build against a poetry application, realizing that you want to drop into the python REPL (or run some other known command/script) to debug something, so setting `BP_POETRY_TARGET="python"` (or whatever debugging script you want), and rebuilding the app. This will be very quick as the filesystem hasn't changed at all so the lifecycle can re-use all the caching.

**Comment by joshuatcasey** [comment]
@robdimsdale I'll note that this changes detection criteria for this buildpack, since if `BP_POETRY_RUN_TARGET` is specified, there's no need to inspect `pyproject.toml`. 

This will be called out in the `README` and godoc in the upcoming PR.
